#Q1

In [1]:
import numpy as np
mat1=np.array([[3,2,1,5],[9,1,3,0]])
mat2=np.array([[2,9,0],[1,3,5],[2,4,7],[8,1,5]])
mulmat=np.dot(mat1,mat2)
print(f"A*B={mulmat}")

A*B=[[50 42 42]
 [25 96 26]]


#Q2

In [2]:
A=np.array([[3,8,-6],[4,10,-1],[-1,9,7]])
detA=np.linalg.det(A)
print(f'A={A}\ndet(A)={detA}')

A=[[ 3  8 -6]
 [ 4 10 -1]
 [-1  9  7]]
det(A)=-254.99999999999991


#Q3

In [3]:
A=np.array([[2,3,1],[3,4,1],[3,7,2]])
inversA=np.linalg.inv(A)
print(f'A={A}\nInvers(A)={inversA}')

A=[[2 3 1]
 [3 4 1]
 [3 7 2]]
Invers(A)=[[ 0.5  0.5 -0.5]
 [-1.5  0.5  0.5]
 [ 4.5 -2.5 -0.5]]


#Q4

In [4]:
A=np.array([[0,1],[-2,-3]])
w,v=np.linalg.eig(A)
print(f'EigenVector={w}\nEigenValues={v}')

EigenVector=[-1. -2.]
EigenValues=[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


#Q5

In [5]:
A=np.array([[5,3,6],[0,-2,1],[4,7,2]])
print(f'MatrixNorm={np.linalg.norm(A)}\nRowNorm={np.linalg.norm(A,axis=1)}\nColumnNorm={np.linalg.norm(A,axis=0)}')

MatrixNorm=12.0
RowNorm=[8.36660027 2.23606798 8.30662386]
ColumnNorm=[6.40312424 7.87400787 6.40312424]


#Q6

In [6]:
a=np.array([[1,-1],[2,-1]])
b=np.array([-1,-5])
x=np.linalg.solve(a,b)
print(x)

[-4. -3.]


Q7

In [7]:
a=np.array([[1,-1,1],[3,1,2],[-5,2,-1]])
b=np.array([10,34,-14])
x=np.linalg.solve(a,b)
print(f'   x  y  z')
print(x)

   x  y  z
[ 2.  4. 12.]
